[project]
name = "mcp_demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-mcp>=0.2.0",
    "mcp>=1.6.0",
    "pydantic>=2.11.3",
    "requests>=2.32.3",
    "uvicorn>=0.34.1",
]
